#!/bin/sh
arch=`uname -m`
neko_dir="/etc/neko"

core_ver="dc2108c1"
url_core="https://github.com/nosignals/neko/releases/download/core"
url_geo="https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest"

echo "Downloading Core Files"

case "$arch" in
aarch64)
	arch="arm64"
	;;
arm)
	arch="armv7"
	;;
x86_64)
	arch="amd64"
	;;
*)
	echo "- NEKO not supported!"
	arch="0"
	;;
esac

if [ $arch == "0" ] ; then
	echo "- ERROR!!! Arch not supported"
else
	echo "- Downloading Mihomo Binary - $arch"
	wget -q -O ${neko_dir}/core/mihomo.gz ${url_core}/mihomo-linux-${arch}-${core_ver}.gz
	gzip -d ${neko_dir}/core/mihomo.gz

	echo "- Downloading GeoIP Files"
	wget -q -O ${neko_dir}/geoip.metadb ${url_geo}/geoip.metadb

	echo "- Downloading GeoSite Files"
	wget -q -O ${neko_dir}/geosite.db ${url_geo}/geosite.db

	chmod +x /etc/init.d/neko
	chmod +x ${neko_dir}/core/*
fi

uci set uhttpd.main.index_page='index.php'
uci set uhttpd.main.interpreter='.php=/usr/bin/php-cgi'
uci commit uhttpd
/etc/init.d/uhttpd restart

uci set neko.cfg.enabled='0'
uci set neko.cfg.php_server='0'
uci commit neko

echo "Done!!!"
rm ${neko_dir}/postinst
exit 0