#!/bin/bash
#
# Copyright (C) 2024 nosignal

neko_status=$(uci -q get neko.cfg.enabled)
neko_new_interface=$(uci -q get neko.cfg.new_interface)
neko_delay=$(uci -q get neko.cfg.delay)
neko_bin="/etc/neko/core/neko"
neko_pid="/etc/neko/tmp/neko_pid.txt"
log="/etc/neko/tmp/log.txt"
firewall="/etc/init.d/firewall"
neko_version=$1

neko_checknewver(){
    new_version=$(curl -m 5 -f -s https://raw.githubusercontent.com/nosignals/neko/luci-app-neko/neko_version)
    if [ $neko_version == $new_version ] || [ -z $new_version ]; then
        strversion="- Latest"
    else
        strversion="- New v.$new_version"
        if [ $1 == "log" ]; then
            echo "[ `date +%T` ] New Version detected. v.$new_version" >> $log
        fi
    fi
}

if [ "$neko_status" == 1 ] && [ "$neko_new_interface" == 1 ]; then
    echo "[ `date +%T` ] - Auto Restart Neko : ON " >> $log
    sleep 20 && neko_checknewver "log"
    while true
    do
        echo "Checking New Interfaces."
        first_iface_cnt=$(ip -o link show | grep -c '^[0-9]\+:')
        sleep "$neko_delay"
        second_iface_cnt=$(ip -o link show | grep -c '^[0-9]\+:')
        
        if [ "$first_iface_cnt" -eq "$second_iface_cnt" ]; then
            if [ -f ${neko_pid} ]; then
                echo "Nothing..."
            else
                break
            fi
        else
            echo "Interface Changed!!!, Restarting Neko"
            echo "[ `date +%T` ] - Detected new Interface, Restarting Neko " >> $log
            $neko_bin -r
            break
            #$firewall reload
        fi
    done
else
    echo "[ `date +%T` ] - Auto Restart Neko : OFF " >> $log
    sleep 20 && neko_checknewver "log"
fi